# Generated by Django 5.2.12 on 2026-03-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_rename_product_add_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_Product',
            new_name='Product',
        ),
    ]
