# Generated by Django 5.2.12 on 2026-03-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_rename_add_product_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='image'),
        ),
    ]
