# Generated by Django 5.2.12 on 2026-03-11 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_remove_product_quantity_alter_product_image'),
        ('user', '0003_remove_cartitems_quantity_cartitems_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.CharField(max_length=100)),
                ('deliverydate', models.CharField(max_length=100)),
                ('orderstatus', models.CharField(max_length=100)),
                ('paymentstatus', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('tracking_id', models.CharField(max_length=100)),
                ('carrier', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.product')),
            ],
        ),
    ]
