# Generated by Django 5.2.12 on 2026-03-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='add_Product',
        ),
    ]
